-- Add sample products for testing category pages
-- This migration adds sample products to test the category functionality

-- First, get the category IDs (we'll use subqueries)
INSERT INTO public.products (
  vendor_id,
  title,
  description,
  price,
  original_price,
  category_id,
  location_id,
  condition,
  brand,
  model,
  images,
  features,
  specifications,
  is_featured,
  is_available
) VALUES 
  -- Electronics products
  (
    (SELECT id FROM auth.users LIMIT 1), -- Use first user as vendor
    'iPhone 15 Pro',
    'Latest iPhone with advanced camera system and A17 Pro chip',
    999.00,
    1099.00,
    (SELECT id FROM public.categories WHERE name = 'Electronics'),
    (SELECT id FROM public.locations WHERE city = 'Lagos'),
    'new',
    'Apple',
    'iPhone 15 Pro',
    '["https://example.com/iphone15.jpg"]',
    '["A17 Pro chip", "48MP camera", "USB-C", "Titanium design"]',
    '{"storage": "256GB", "color": "Natural Titanium", "screen": "6.1 inch"}',
    true,
    true
  ),
  (
    (SELECT id FROM auth.users LIMIT 1),
    'Samsung Galaxy S24',
    'Premium Android smartphone with AI features',
    899.00,
    999.00,
    (SELECT id FROM public.categories WHERE name = 'Smartphones'),
    (SELECT id FROM public.locations WHERE city = 'Lagos'),
    'new',
    'Samsung',
    'Galaxy S24',
    '["https://example.com/galaxy-s24.jpg"]',
    '["AI features", "50MP camera", "Wireless charging", "IP68 rating"]',
    '{"storage": "128GB", "color": "Titanium Gray", "screen": "6.2 inch"}',
    true,
    true
  ),
  (
    (SELECT id FROM auth.users LIMIT 1),
    'MacBook Pro M3',
    'Professional laptop with M3 chip for creators',
    1999.00,
    2199.00,
    (SELECT id FROM public.categories WHERE name = 'Laptops'),
    (SELECT id FROM public.locations WHERE city = 'Abuja'),
    'new',
    'Apple',
    'MacBook Pro',
    '["https://example.com/macbook-pro.jpg"]',
    '["M3 chip", "14-inch display", "18-hour battery", "Liquid Retina XDR"]',
    '{"storage": "512GB", "memory": "16GB", "screen": "14 inch"}',
    true,
    true
  ),
  (
    (SELECT id FROM auth.users LIMIT 1),
    'Sony WH-1000XM5',
    'Industry-leading noise canceling headphones',
    399.00,
    449.00,
    (SELECT id FROM public.categories WHERE name = 'Headphones'),
    (SELECT id FROM public.locations WHERE city = 'Lagos'),
    'new',
    'Sony',
    'WH-1000XM5',
    '["https://example.com/sony-headphones.jpg"]',
    '["Noise canceling", "30-hour battery", "Quick charge", "Hi-Res Audio"]',
    '{"driver": "30mm", "frequency": "4Hz-40kHz", "weight": "250g"}',
    true,
    true
  ),
  (
    (SELECT id FROM auth.users LIMIT 1),
    'PlayStation 5',
    'Next-generation gaming console',
    499.00,
    599.00,
    (SELECT id FROM public.categories WHERE name = 'Gaming'),
    (SELECT id FROM public.locations WHERE city = 'Kano'),
    'new',
    'Sony',
    'PlayStation 5',
    '["https://example.com/ps5.jpg"]',
    '["4K gaming", "Ray tracing", "SSD storage", "DualSense controller"]',
    '{"storage": "825GB", "resolution": "4K", "frame_rate": "120fps"}',
    true,
    true
  ),
  (
    (SELECT id FROM auth.users LIMIT 1),
    'Car Phone Mount',
    'Universal smartphone car mount with wireless charging',
    29.99,
    39.99,
    (SELECT id FROM public.categories WHERE name = 'Automotive'),
    (SELECT id FROM public.locations WHERE city = 'Lagos'),
    'new',
    'TechGear',
    'Universal Mount',
    '["https://example.com/car-mount.jpg"]',
    '["Wireless charging", "360° rotation", "One-hand operation", "Anti-slip"]',
    '{"compatibility": "Universal", "charging": "15W", "material": "ABS"}',
    false,
    true
  ),
  (
    (SELECT id FROM auth.users LIMIT 1),
    'Dash Camera',
    '4K dash cam with night vision and GPS',
    149.00,
    199.00,
    (SELECT id FROM public.categories WHERE name = 'Automotive'),
    (SELECT id FROM public.locations WHERE city = 'Abuja'),
    'new',
    'RoadGuard',
    'RG-4K',
    '["https://example.com/dash-cam.jpg"]',
    '["4K recording", "Night vision", "GPS tracking", "Loop recording"]',
    '{"resolution": "4K", "storage": "128GB", "battery": "Built-in"}',
    false,
    true
  ),
  (
    (SELECT id FROM auth.users LIMIT 1),
    'Car Air Freshener',
    'Long-lasting car air freshener with lavender scent',
    12.99,
    15.99,
    (SELECT id FROM public.categories WHERE name = 'Automotive'),
    (SELECT id FROM public.locations WHERE city = 'Port Harcourt'),
    'new',
    'FreshAir',
    'Lavender',
    '["https://example.com/air-freshener.jpg"]',
    '["Lavender scent", "60-day duration", "Easy installation", "Non-toxic"]',
    '{"duration": "60 days", "scent": "Lavender", "size": "Standard"}',
    false,
    true
  ),
  (
    (SELECT id FROM auth.users LIMIT 1),
    'Bluetooth Adapter',
    'Wireless Bluetooth adapter for car audio',
    39.99,
    49.99,
    (SELECT id FROM public.categories WHERE name = 'Automotive'),
    (SELECT id FROM public.locations WHERE city = 'Ibadan'),
    'new',
    'AudioLink',
    'BT-2000',
    '["https://example.com/bluetooth-adapter.jpg"]',
    '["Bluetooth 5.0", "Auto-connect", "Noise reduction", "USB charging"]',
    '{"bluetooth": "5.0", "range": "10m", "battery": "8 hours"}',
    false,
    true
  ),
  (
    (SELECT id FROM auth.users LIMIT 1),
    'Nike Air Max 270',
    'Comfortable running shoes with Air Max technology',
    120.00,
    150.00,
    (SELECT id FROM public.categories WHERE name = 'Fashion'),
    (SELECT id FROM public.locations WHERE city = 'Lagos'),
    'new',
    'Nike',
    'Air Max 270',
    '["https://example.com/nike-shoes.jpg"]',
    '["Air Max cushioning", "Breathable upper", "Rubber outsole", "Lightweight"]',
    '{"size": "US 9", "color": "White/Black", "material": "Mesh/Synthetic"}',
    false,
    true
  );
