// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgtvnkohajcqknuiwvyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtndHZua29oYWpjcWtudWl3dnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzExODcsImV4cCI6MjA2NTUwNzE4N30.ePeeM9_HCCgPfT9PPzqblLmUxv1WsiEwOL_E3Isej4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);